//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaFood.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class AdminUser
    {
        [DisplayName("Mã ID")]
        [Required(ErrorMessage = "Không được trống")]
        public int ID { get; set; }
        [DisplayName("Tên đăng nhập")]
        [Required(ErrorMessage = "Không được trống")]
        public string NameUser { get; set; }
        [DisplayName("Chức vụ")]
        [Required(ErrorMessage = "Không được trống")]
        public string RoleUser { get; set; }
        [DisplayName("Mật khẩu")]
        [Required(ErrorMessage = "Không được trống")]
        public string PasswordUser { get; set; }
    }
}
