//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaFood.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.OrderProes = new HashSet<OrderPro>();
        }

        [DisplayName("Số điện thoại")]
        [Required(ErrorMessage = "Không được trống")]
        public int IDCus { get; set; }

        [DisplayName("Tên đăng nhập")]
        [Required(ErrorMessage = "Không được trống")]
        public string NameCus { get; set; }

        [DisplayName("Nhập lại số điện thoại")]
        [Required(ErrorMessage = "Không được trống")]
        public string PhoneCus { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "Không được trống")]
        public string EmailCus { get; set; }
        [DisplayName("Mật khẩu")]
        [Required(ErrorMessage = "Không được trống")]
        public string PasswordCus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPro> OrderProes { get; set; }
        [NotMapped]
        [DisplayName("Nhập lại mật khẩu")]
        [Required(ErrorMessage = "Không được trống")]
        [Compare("PasswordCus")]
        public string RePass { get; set; }
    }
}
